version: 2.1
jobs:
  build:
    working_directory: ~/1CircleCI/repo
    docker:
      - image: circleci/python:3.7-node # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Install dependencies"
          command: | # use pipenv to install dependencies
            sudo pip install pandas
            sudo pip install pipenv
            sudo pip install PyUnitReport
            sudo pip install unittest-xml-reporting
            pipenv install
      - run:
          name: "test_item_details.py html format"
          command: |
            cd test_framework
            export PYTHONPATH=$PYTHONPATH:.
            python test/test_item_details.py -v
      - store_test_results:
            path: test_framework/reports
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test_framework/reports
          destination: tr1

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  schedule-workflow:
    triggers:
      - schedule:
          cron: "45 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build