version: 2.1
jobs:
  build:
    working_directory: ~/1CircleCI/repo
    docker:
      - image: circleci/python:3.7-node # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Install dependencies"
          command: | # use pipenv to install dependencies
            sudo pip install pandas
            sudo pip install pipenv
            sudo pip install PyUnitReport
            sudo pip install unittest-xml-reporting
            pipenv install
      - run:
          name: "test_rows.py "
          halt_build_on_fail: false
          when: always
          command: |
            echo 'running test_rows.py...'
            cd test_framework
            export PYTHONPATH=$PYTHONPATH:.
            export VIZIO_TEST_ENV=prod
            python test/test_rows.py -v > test_rows
            python test/send_report.py test_rows
      - store_test_results:
            path: test_framework/reports
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test_framework/reports
          destination: tr1
  test:
    working_directory: ~/1CircleCI/repo
    docker:
      - image: circleci/python:3.7-node # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Install dependencies"
          command: | # use pipenv to install dependencies
            sudo pip install pandas
            sudo pip install pipenv
            sudo pip install PyUnitReport
            sudo pip install unittest-xml-reporting
            pipenv install
      - run:
          name: "test_item_details.py "
          halt_build_on_fail: false
          when: always
          command: |
            cd test_framework
            export PYTHONPATH=$PYTHONPATH:.
            export VIZIO_TEST_ENV=prod
            python test/test_item_details.py -v > test_item_details
            python test/send_report.py test_item_details
      - store_test_results:
            path: test_framework/reports
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test_framework/reports
          destination: tr1
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - test
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    triggers:
      - schedule:
          cron: "10 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test

