version: 2.1
jobs:
  build:
    working_directory: ~/1CircleCI/repo
    docker: 
      - image: circleci/python:3.7-node # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Install dependencies"
          command: | # use pipenv to install dependencies
            sudo pip install pandas
            sudo pip install pipenv
            sudo pip install PyUnitReport
            sudo pip install unittest-xml-reporting
            pipenv install
      - run:
          name: "test_catalog.py "
          command: |
            cd test_framework
            export PYTHONPATH=$PYTHONPATH:.
            mkdir -p ./gtest_results
            ls ./gtest_results
            python3 test/test_catalog.py catalog-dev.smartcasttv.com api-stage.vizio.com -v >> ./gtest_results/catalog_comparison_test_$DATE.log 2>&1
      - store_test_results:
            path: test_framework/gtest_results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test_framework/gtest_results 
          destination: tr1
