version: 2.1
jobs:
  build:
    working_directory: ~/1CircleCI/repo
    docker: 
      - image: circleci/python:3.7-node # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: | # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python --version 
            mkdir -p /tmp/test-results
            python test_hello.py
