version: 2.1
jobs:
  build:
    working_directory: ~/1CircleCI/repo
    docker: 
      - image: circleci/python:3.7-node # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: | # use pipenv to install dependencies
            sudo pip install pandas
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python --version 
            mkdir -p ~/test-results
            touch ~/test-results/report.html
            cd test_framework
            export PYTHONPATH=$PYTHONPATH:.
      - run:
          command: |
            python -m unittest test.test_catalog.CatalogTest.test_catalog_row_title
      - run:
          command: |
            python test_three.py

      - store_test_results:
            path: ~/test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
